name: Notify Discord on Push

on:
  push:
    branches:
        main:
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Send notification to Discord
      uses: Ilshidur/action-discord-webhook@2.0.0
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        username: GitHub Actions
        content: "Novo commit no repositório! :rocket:"
