name: Discord Webhook

on:
  push:
    branches:
      - main  # Aqui está correto monitorar o branch main, se for esse o nome do seu branch principal

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "Novo commit no repositório!"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

