name: Docker Image CI and Discord Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura o Docker para rodar
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Faz o login no DockerHub usando as credenciais dos segredos que você criou
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Constrói a imagem Docker da sua aplicação
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-todo-app:latest

      # Verifica se a imagem foi construída corretamente
      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}

  notify:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Faz o checkout do repositório
      - uses: actions/checkout@v2

      # Envia a notificação para o Discord
      - name: Run Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
